namespace: "markuman"
description: bring up your nextcloud usage to the next level 🚀
name: "nextcloud"
version: "10.0.0"
readme: "README.md"
authors:
    - "Markus Bergholz <markuman+spambelongstogoogle@gmail.com>"
license:
    - "GPL-3.0-or-later"
tags:
    - nextcloud
    - collection
    - devops
    - installation
    - setup
repository: "https://github.com/markuman/markuman.nextcloud"
issues: "https://github.com/markuman/markuman.nextcloud/issues"
dependencies:
  devsec.hardening: '>=8.0.0'
