- name: set hostname
  ansible.builtin.hostname:
    name: "{{ nextcloud_fqdn.split('.')[0] }}"

- name: complete /etc/hosts
  ansible.builtin.lineinfile:
    name: /etc/hosts
    line: "127.0.1.1 {{ nextcloud_fqdn }} {{ nextcloud_fqdn.split('.')[0] }}"

- name: upgrade all packages first
  ansible.builtin.apt:
    update_cache: true
    state: latest
    upgrade: true

- name: install php and mariadb
  ansible.builtin.apt:
    update_cache: true
    state: latest
    name:
      - mariadb-server
      - mariadb-client
      - ufw
      - vnstat
      - python3-pymysql
      - unzip
      - php-fpm
      - php-gd
      - php-mysql
      - php-curl
      - php-xml
      - php-zip
      - php-intl
      - php-mbstring
      - php-bz2
      - php-json
      - php-apcu
      - php-imagick
      - php-gmp
      - php-bcmath
      - imagemagick
      - libmagickcore-6.q16-6-extra
      - fail2ban

- name: install redis
  when: install_redis
  ansible.builtin.apt:
    update_cache: true
    state: latest
    name:
      - redis-server
      - php8.1-redis

- name: enable ipv6 for ufw
  ansible.builtin.lineinfile:
    name: /etc/default/ufw
    regexp: IPV6=no
    line: IPV6=yes
  notify:
    - reload ufw

- name: ufw rules
  ansible.builtin.command: "{{ item }}"
  with_items:
    - ufw limit ssh comment "incomming ssh with ratelimit"
    - ufw allow out 22 comment "outgoing ssh"
    - ufw allow 80 comment "incomming http for caddy"
    - ufw allow 443 comment "incomming https for caddy"
    - ufw allow out 80 comment "outgoing http"
    - ufw allow out 443 comment "outgoing https"
    - ufw allow out 53/udp comment "outgoing for dns"
    - ufw allow out 123/udp comment "outgoing for ntp"
    - ufw allow out 993 comment "outgoing imap ssl"
    - ufw allow out 465 comment "outgoing smtp ssl"

- name: ufw enable
  community.general.ufw:
    state: enabled

- name: os hardening
  ansible.builtin.include_role:
    name: devsec.hardening.os_hardening

- name: flush handlers for os hardening
  ansible.builtin.meta: flush_handlers
