- name: Install caddy for linux_amd64 from github releases
  ansible.builtin.apt:
    deb: "https://github.com/caddyserver/caddy/releases/download/v{{ caddy_version }}/caddy_{{ caddy_version }}_linux_amd64.deb"
  when: ansible_facts['architecture'] == 'x86_64'

- name: Install caddy for linux_arm64 from github releases
  ansible.builtin.apt:
    deb: "https://github.com/caddyserver/caddy/releases/download/v{{ caddy_version }}/caddy_{{ caddy_version }}_linux_arm64.deb"
  when: ansible_facts['architecture'] == 'aarch64'
  
- name: change caddy user to www-data
  ansible.builtin.lineinfile:
    mode: '0755'
    owner: root
    group: root
    dest: /lib/systemd/system/caddy.service
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - regexp: User=.*
      line: User=www-data
    - regexp: Group=.*
      line: Group=www-data

- name: create www/.local directory for caddy
  ansible.builtin.file:
    path: /var/www/.local
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: chown /var/log/caddy folder for www-data
  ansible.builtin.file:
    path: /var/log/caddy
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'
  notify:
    - restart caddy

- name: caddy config
  ansible.builtin.template:
    dest: /etc/caddy/Caddyfile
    src: caddyfile.j2
  notify:
    - restart caddy

- name: flush handlers after caddy configuration
  ansible.builtin.meta: flush_handlers
